"""product tags

Revision ID: 5dbc44d64b6a
Revises: 618cc6109657
Create Date: 2026-07-04 07:33:30.516372
"""
from typing import Sequence, Union

from alembic import op
import sqlalchemy as sa
from sqlalchemy.dialects import postgresql

# revision identifiers, used by Alembic.
revision: str = '5dbc44d64b6a'
down_revision: Union[str, None] = '618cc6109657'
branch_labels: Union[str, Sequence[str], None] = None
depends_on: Union[str, Sequence[str], None] = None


def upgrade() -> None:
    # Backfill existing rows with an empty array via server_default, then drop it.
    op.add_column(
        'products',
        sa.Column(
            'tags',
            postgresql.JSONB(astext_type=sa.Text()),
            nullable=False,
            server_default=sa.text("'[]'::jsonb"),
        ),
    )
    op.alter_column('products', 'tags', server_default=None)


def downgrade() -> None:
    # ### commands auto generated by Alembic - please adjust! ###
    op.drop_column('products', 'tags')
    # ### end Alembic commands ###
