"""unique payment checkout_request_id

Revision ID: 618cc6109657
Revises: 9ca9daf476db
Create Date: 2026-07-04 01:08:30.197185
"""
from typing import Sequence, Union

from alembic import op
import sqlalchemy as sa


# revision identifiers, used by Alembic.
revision: str = '618cc6109657'
down_revision: Union[str, None] = '9ca9daf476db'
branch_labels: Union[str, Sequence[str], None] = None
depends_on: Union[str, Sequence[str], None] = None


def upgrade() -> None:
    # ### commands auto generated by Alembic - please adjust! ###
    op.drop_index('ix_payments_checkout_request_id', table_name='payments')
    op.create_index(op.f('ix_payments_checkout_request_id'), 'payments', ['checkout_request_id'], unique=True)
    # ### end Alembic commands ###


def downgrade() -> None:
    # ### commands auto generated by Alembic - please adjust! ###
    op.drop_index(op.f('ix_payments_checkout_request_id'), table_name='payments')
    op.create_index('ix_payments_checkout_request_id', 'payments', ['checkout_request_id'], unique=False)
    # ### end Alembic commands ###
